<?php
/**
 * Plugin Name: States and cities
 * Plugin URI: https://github.com/YasirGaji/state-cities.git
 * Author: Yasir Gaji
 * Author URI: https://github.com/YasirGaji/state-cities.git
 * Description: Adds a thrid level city to state
 * Version: 0.1.0
 * License: GPL2 or later
 * License URL: http://www.gnu.org/licenses/gpl-2.0.txt
 * text-domain: states-cities
*/

defined( 'ABSPATH') or die('Please get proper access');

/**
 * Add cities to Woocommerce. Needs WC City Select (https://wordpress.org/plugins/wc-city-select/) plugin installed.
 * Replace XX with the country code. Instead of YYY, ZZZ use actual state codes.
 * Pick countried from https://github.com/woocommerce/woocommerce/blob/master/i18n/countries.php
 * Pick states from https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php
 */ 

// Add aplugin notice to check for WC city Select as active plugin.
add_action( 'plugins_loaded', 'check_for_wc_city_select_active' );

function check_for_wc_city_select_active() {
    if( ! class_exists( 'WC_City_Select' ) ) {
        add_action( 'admin_notices', 'notice_wc_city_select_activate' );
        return;
    }

    add_filter( 'wc_city_select_cities', 'techiepress_my_cities' );
}

function notice_wc_city_select_activate() {
    $message = sprintf( __( 'States and cities for Woocommerce requires the <a href="%s">WC City Select</a> plugin to be active', 'states-and-cities-for-woocommerce' ), 'https://wordpress.org/plugins/wc-city-select/' );
    printf( '<div class="error notice-error notice is-dismissible"><p>%s</p></div>', $message );
}

function techiepress_my_cities( $cities ) {

    $cities['NG'] = array(
      'AB' => array(
        'Aba North',
        'Aba South',
        'Arochukwu',
        'Bende',
        'Ikwano',
        'Isiala Ngwa North',
        'Isiala Ngwa South',
        'Isuikwuato',
        'Obingwa',
        'Ohafia',
        'Osisioma',
        'Ugwunagbo',
        'Ukwa East',
        'Ukwa West',
        'Umuahia North',
        'Umuahia South',
        'Umuneochi'
        ),
        'AD' => array(
          'Demsa',
          'Fufore',
          'Ganaye',
          'Gireri',
          'Gombi',
          'Guyuk',
          'Hong',
          'Jada',
          'Lamurde',
          'Madagali',
          'Maiha',
          'Mayo-Belwa',
          'Michika',
          'Mubi North',
          'Mubi South',
          'Numan',
          'Shelleng',
          'Song',
          'Toungo',
          'Yola North',
          'Yola South'
        ),
        'AK' => array(
          'Abak',
          'Eastern Obolo',
          'Eket',
          'Esit Eket',
          'Essien Udim',
          'Etim Ekpo',
          'Etinan',
          'Ibeno',
          'Ibesikpo Asutan',
          'Ibiono Ibom',
          'Ika',
          'Ikono',
          'Ikot Abasi',
          'Ikot Ekpene',
          'Ini',
          'Itu',
          'Mbo',
          'Mkpat Enin',
          'Nsit Atai',
          'Nsit Ibom',
          'Nsit Ubium',
          'Obot Akara',
          'Okobo',
          'Onna',
          'Oron',
          'Oruk Anam',
          'Udung Uko',
          'Ukanafun',
          'Uruan',
          'Urue-Offong/Oruko',
          'Uyo'
        ),
        'AN' => array(
          'Aguata',
          'Anambra East',
          'Anambra West',
          'Anaocha',
          'Awka North',
          'Awka South',
          'Ayamelum',
          'Dunukofia',
          'Ekwusigo',
          'Idemili North',
          'Idemili south',
          'Ihiala',
          'Njikoka',
          'Nnewi North',
          'Nnewi South',
          'Ogbaru',
          'Onitsha North',
          'Onitsha South',
          'Orumba North',
          'Orumba South',
          'Oyi'
        ),
        'BA' => array(
          'Alkaleri',
          'Bauchi',
          'Bogoro',
          'Damban',
          'Darazo',
          'Dass',
          'Ganjuwa',
          'Giade',
          'Itas/Gadau',
          'Jama\'are',
          'Katagum',
          'Kirfi',
          'Misau',
          'Ningi',
          'Shira',
          'Tafawa-Balewa',
          'Toro',
          'Warji',
          'Zaki'
        ),
        'BY' => array(
          'Brass',
          'Ekeremor',
          'Kolokuma/Opokuma',
          'Nembe',
          'Ogbia',
          'Sagbama',
          'Southern Jaw',
          'Yenegoa'
        ),
        'BE' => array(
          'Ado',
          'Agatu',
          'Apa',
          'Buruku',
          'Gboko',
          'Guma',
          'Gwer East',
          'Gwer West',
          'Katsina-Ala',
          'Konshisha',
          'Kwande',
          'Logo',
          'Makurdi',
          'Obi',
          'Ogbadibo',
          'Oju',
          'Okpokwu',
          'Ohimini',
          'Oturkpo',
          'Tarka',
          'Ukum',
          'Ushongo',
          'Vandeikya'
        ),
        'BO' => array(
          'Abadam',
          'Askira/Uba',
          'Bama',
          'Bayo',
          'Biu',
          'Chibok',
          'Damboa',
          'Dikwa',
          'Gubio',
          'Guzamala',
          'Gwoza',
          'Hawul',
          'Jere',
          'Kaga',
          'Kala/Balge',
          'Konduga',
          'Kukawa',
          'Kwaya Kusar',
          'Mafa',
          'Magumeri',
          'Maiduguri',
          'Marte',
          'Mobbar',
          'Monguno',
          'Ngala',
          'Nganzai',
          'Shani'
        ),
        'CR' => array(
          'Akpabuyo',
          'Odukpani',
          'Akamkpa',
          'Biase',
          'Abi',
          'Ikom',
          'Yarkur',
          'Odubra',
          'Boki',
          'Ogoja',
          'Yala',
          'Obanliku',
          'Obudu',
          'Calabar South',
          'Etung',
          'Bekwara',
          'Bakassi',
          'Calabar Municipality'
        ),
        'DE' => array(
          'Oshimili',
          'Aniocha',
          'Aniocha South',
          'Ika South',
          'Ika North-East',
          'Ndokwa West',
          'Ndokwa East',
          'Isoko south',
          'Isoko North',
          'Bomadi',
          'Burutu',
          'Ughelli South',
          'Ughelli North',
          'Ethiope West',
          'Ethiope East',
          'Sapele',
          'Okpe',
          'Warri North',
          'Warri South',
          'Uvwie',
          'Udu',
          'Warri Central',
          'Ukwani',
          'Oshimili North',
          'Patani'
        ),
        'EB' => array(
          'Afikpo South',
          'Afikpo North',
          'Onicha',
          'Ohaozara',
          'Abakaliki',
          'Ishielu',
          'lkwo',
          'Ezza',
          'Ezza South',
          'Ohaukwu',
          'Ebonyi',
          'Ivo'
        ),
        'ED'  => array(
          'Esan North-East',
          'Esan Central',
          'Esan West',
          'Egor',
          'Ukpoba',
          'Central',
          'Etsako Central',
          'Igueben',
          'Oredo',
          'Ovia SouthWest',
          'Ovia South-East',
          'Orhionwon',
          'Uhunmwonde',
          'Etsako East',
          'Esan South-East'
        ),
        'EK' => array(
          'Ado',
          'Ekiti-East',
          'Ekiti-West',
          'Emure/Ise/Orun',
          'Ekiti South-West',
          'Ikare',
          'Irepodun',
          'Ijero',
          'Ido/Osi',
          'Oye',
          'Ikole',
          'Moba',
          'Gbonyin',
          'Efon',
          'Ise/Orun',
          'Ilejemeje'
        ),
        'EN' => array(
          'Enugu South',
          'Igbo-Eze South',
          'Enugu North',
          'Nkanu',
          'Udi Agwu',
          'Oji-River',
          'Ezeagu',
          'IgboEze North',
          'Isi-Uzo',
          'Nsukka',
          'Igbo-Ekiti',
          'Uzo-Uwani',
          'Enugu East',
          'Aninri',
          'Nkanu East',
          'Udenu'
        ),
        'GO' => array(
          'Akko',
          'Balanga',
          'Billiri',
          'Dukku',
          'Kaltungo',
          'Kwami',
          'Shomgom',
          'Funakaye',
          'Gombe',
          'Nafada/Bajoga',
          'Yamaltu/Delta'
        ),
        'IM' => array(
          'Aboh-Mbaise',
          'Ahiazu-Mbaise',
          'Ehime-Mbano',
          'Ezinihitte',
          'Ideato North',
          'Ideato South',
          'Ihitte/Uboma',
          'Ikeduru',
          'Isiala Mbano',
          'Isu',
          'Mbaitoli',
          'Mbaitoli',
          'Ngor-Okpala',
          'Njaba',
          'Nwangele',
          'Nkwerre',
          'Obowo',
          'Oguta',
          'ehime-mbano',
          'Ohaji/Egbema',
          'Okigwe',
          'Orlu',
          'Orsu',
          'Oru East',
          'Oru West',
          'Owerri-Municipal',
          'Owerri North',
          'Owerri West'
        ),
        'JI' => array(
          'Auyo',
          'Babura',
          'Birni Kudu',
          'Biriniwa',
          'Buji',
          'Dutse',
          'Gagarawa',
          'Garki',
          'Gumel',
          'Guri',
          'Gwaram',
          'Gwiwa',
          'Hadejia',
          'Jahun',
          'Kafin Hausa',
          'Kaugama Kazaure',
          'Kiri Kasamma',
          'Kiyawa',
          'Maigatari',
          'Malam Madori',
          'Miga',
          'Ringim',
          'Roni',
          'Sule-Tankarkar',
          'Taura',
          'Yankwashi'
        ),
        'KD' => array(
          'Birni-Gwari',
          'Chikun',
          'Giwa',
          'Igabi',
          'Ikara',
          'jaba',
          'Jema\'a',
          'Kachia',
          'Kaduna North',
          'Kaduna South',
          'Kagarko',
          'Kajuru',
          'Kaura',
          'Kauru',
          'Kubau',
          'Kudan',
          'Lere',
          'Makarfi',
          'Sabon-Gari',
          'Sanga',
          'Soba',
          'Zango-Kataf',
          'Zaria'
        ),
        'KE' => array(
          'Aleiro',
          'Arewa-Dandi',
          'Argungu',
          'Augie',
          'Bagudo',
          'Birnin Kebbi',
          'Bunza',
          'Dandi',
          'Fakai',
          'Gwandu',
          'Jega',
          'Kalgo',
          'Koko/Besse',
          'Maiyama',
          'Ngaski',
          'Sakaba',
          'Shanga',
          'Suru',
          'Wasagu/Danko',
          'Yauri',
          'Zuru'
        ),
        'KN' => array(
          'Ajingi',
          'Albasu',
          'Bagwai',
          'Bebeji',
          'Bichi',
          'Bunkure',
          'Dala',
          'Dambatta',
          'Dawakin Kudu',
          'Dawakin Tofa',
          'Doguwa',
          'Fagge',
          'Gabasawa',
          'Garko',
          'Garum Mallam',
          'Gaya',
          'Gezawa',
          'Gwale',
          'Gwarzo',
          'Kabo',
          'Kano Municipal',
          'Karaye',
          'Kibiya',
          'Kiru',
          'kumbotso',
          'Kunchi',
          'Kura',
          'Madobi',
          'Makoda',
          'Minjibir',
          'Nasarawa',
          'Rano',
          'Rimin Gado',
          'Rogo',
          'Shanono',
          'Sumaila',
          'Takali',
          'Tarauni',
          'Tofa',
          'Tsanyawa',
          'Tudun Wada',
          'Ungogo',
          'Warawa',
          'Wudil'
        ),
        'KT' => array(
          'Bakori',
          'Batagarawa',
          'Batsari',
          'Baure',
          'Bindawa',
          'Charanchi',
          'Dandume',
          'Danja',
          'Dan Musa',
          'Daura',
          'Dutsi',
          'Dutsin-Ma',
          'Faskari',
          'Funtua',
          'Ingawa',
          'Jibia',
          'Kafur',
          'Kaita',
          'Kankara',
          'Kankia',
          'Katsina',
          'Kurfi',
          'Kusada',
          'Mai\'Adua',
          'Malumfashi',
          'Mani',
          'Mashi',
          'Matazu',
          'Musawa',
          'Rimi',
          'Sabuwa',
          'Safana',
          'Sandamu',
          'Zango'
        ),
        'KO' => array(
          'Adavi',
          'Ajaokuta',
          'Ankpa',
          'Bassa',
          'Dekina',
          'Ibaji',
          'Idah',
          'Igalamela-Odolu',
          'Ijumu',
          'Kabba/Bunu',
          'Kogi',
          'Lokoja',
          'Mopa-Muro',
          'Ofu',
          'Ogori/Mangongo',
          'Okehi',
          'Okene',
          'Olamabolo',
          'Omala',
          'Yagba East',
          'Yagba West'
        ),
        'KW' => array(
          'Asa',
          'Baruten',
          'Edu',
          'Ekiti',
          'Ifelodun',
          'Ilorin East',
          'Ilorin West',
          'Ilorin South',
          'Ilorin North',
          'Irepodun',
          'Isin',
          'Kaiama',
          'Moro',
          'Offa',
          'Oke-Ero',
          'Oyun',
          'Pategi'
        ),
        'LA' => array(
          'Abijo',
      'Abuja',
      'Abule Egba',
      'Abule Oja',
      'Abule Oshun',
      'Abule Taylor',
      'Abulegba',
      'Addo',
      'Agbado',
      'Agbara',
      'Agbelekale',
      'Agboju',
      'Agbule egba',
      'Agege',
      'Agidingbi',
      'Ago Palace Okota',
      'Ago Palace way',
      'Aguda',
      'Agungi',
      'Ajah',
      'Ajangbadi',
      'Ajao',
      'Ajao Estate',
      'Ajegunle',
      'Ajegunle - apapa',
      'Ajuwon',
      'Akesan',
      'Akoka',
      'Akowonjo',
      'Alaba',
      'Alaba Oro',
      'Alaba Rago',
      'Alafia',
      'Alagbado',
      'Alagbole',
      'Alakija',
      'Alakuko',
      'Alapere',
      'Alausa',
      'Alegba',
      'Alimosho',
      'ALIMOSHO',
      'Allen Avenue',
      'Amukoko',
      'Amuwo Odofin',
      'Amuwo-Odifin',
      'Amuwo-Odofin',
      'Anthony',
      'Anthony Oke',
      'Anthony Village',
      'Apapa',
      'Apongbon',
      'Aseese',
      'Aspamda',
      'Awoyaya',
      'Ayobo',
      'Ayobo-Ipaja',
      'Badagry',
      'Badia',
      'Badore',
      'Balogun',
      'Bariga',
      'Berger',
      'Chevron',
      'City Hall',
      'Coker',
      'Costain',
      'Dopemu',
      'Ebute Metta',
      'Ebute-Meta',
      'Ebute-Metta',
      'Egan',
      'Egbe',
      'Egbe Idimu',
      'Egbeda',
      'Egbeda,',
      'Ejigbo',
      'Epe',
      'Ereko',
      'Fadeyi',
      'Fagba',
      'Festac',
      'Festac Town',
      'FESTAC Town,',
      'Fola Agoro',
      'Gbagada',
      'Iba',
      'Ibadan',
      'Ibeju-Lekki',
      'Iddo',
      'Idi Araba',
      'Idimu',
      'Idimu-ikotun',
      'Idiroko',
      'Ifako',
      'Ifako Ijaiye',
      'Ifako-Agege',
      'Ifako-Gbagada',
      'Ifako-Ijaiye',
      'Igando',
      'Igando-Egan',
      'Iganmu',
      'Igbobi',
      'Igbogbo',
      'Iguando',
      'Ijaiye',
      'Ijaiye Ojokoro',
      'Ijanikin',
      'Ijaye Ojokoro',
      'Ijaye-Ojokoro',
      'Ijebu Lekki',
      'Ijegun',
      'Ijesha',
      'Ijeshatedo',
      'Ijora',
      'Iju',
      'Iju Agege',
      'Iju Ishaga',
      'Iju-Ishaga',
      'Ikeja',
      'Ikorodu',
      'Ikosi',
      'Ikota',
      'Ikotun',
      'Ikotun Egbe',
      'Ikoyi',
      'Ilasa',
      'Ilasamaja',
      'ilawe',
      'Ile-Iwe',
      'Ilewe',
      'Ilorin',
      'Ilupeju',
      'Ipaja',
      'Iresi',
      'Ishaga',
      'Isheri',
      'Isheri Olofin',
      'Isheri Olowora',
      'Isolo',
      'Itire',
      'Iwaya',
      'Iworo',
      'IYANA IPAJA',
      'Iyana Ipaja',
      'Iyana Isashi',
      'Iyana Paja',
      'Iyanoba',
      'Jakande',
      'Jibowu',
      'Katcha',
      'Ketu',
      'Kirikiri',
      'Kontagoro',
      'Kosofe',
      'Kuje',
      'Ladipo',
      'Lagos Island',
      'Lawanson',
      'Lekki',
      'Lekki Phase 1',
      'Lekki Phase 2',
      'lkeja',
      'lkotun',
      'llupeju',
      'lsolo',
      'Mafoluku',
      'Magboro-Akeran',
      'Magodo',
      'Magodo GRA',
      'Magodo phase 2',
      'Makoko',
      'Marina',
      'Maryland',
      'Matori',
      'Maza Maza',
      'Meiran',
      'Mende Maryland',
      'Mile 12',
      'Mile 2',
      'Mofaluku',
      'morogbo',
      'Mulero',
      'mushin',
      'New Road',
      'Obalende',
      'Obanikoro',
      'Obawole',
      'Odi-olowo',
      'Odugu-Ojota',
      'Odunade, Orile/Coker',
      'Ogba',
      'Ogba-ijaiye',
      'Ogudu',
      'Oja',
      'Oja Oba',
      'Ojata',
      'Ojo',
      'Ojo Alaba',
      'Ojo Alaba International',
      'Ojo-Alaba',
      'Ojodu',
      'Ojodu - Berger',
      'Ojodu Berger',
      'Ojodu-Berger',
      'Ojokoro',
      'Ojokoro-Ijaiye',
      'Ojota',
      'Ojuelegba',
      'Oke Arin',
      'Oke Ira',
      'Oke Odo',
      'Oke-Afa',
      'Oko-Oba',
      'Okoko',
      'Okokomaiko',
      'Okomalam',
      'Okota',
      'Okota, Isolo',
      'Okta',
      'Olodi',
      'Olowara',
      'Olowora',
      'Oluti-Amuwo',
      'Omole',
      'Omole Phase 1',
      'Onikan',
      'Onipan',
      'Onipanu',
      'Oniru',
      'Opebi',
      'Oregun',
      'Oriade',
      'Orile',
      'Orile Coker',
      'Orile Iganmu',
      'Orilowo Ejigbo',
      'Orinsubare',
      'Osapa',
      'Oshodi',
      'Oshodi Apapa',
      'Oshodi Isolo',
      'Oshodi Mafoluku',
      'Oshodi-Isolo',
      'Oshodi/ Isolo',
      'Osodi-Isolo',
      'Osogbo',
      'Otto',
      'Owode',
      'Oworonshoki',
      'Oyingbo',
      'Palmgrove',
      'Pedro',
      'Phase I',
      'Sabo',
      'Sabo Yaba',
      'Sangisha',
      'Sango',
      'Sangotedo',
      'Sangross',
      'Sari Iganmu',
      'Satellite',
      'Satellite Town',
      'Shaha',
      'Shangisha',
      'Shasha',
      'Shogunle',
      'Sholuyi Gbagada',
      'Shomolu',
      'Snake Island',
      'Somolu',
      'Surulere',
      'Tejuosho',
      'VGC',
      'Victoria Island',
      'Yaba',
        ),
        'NA' => array(
          'Akwanga',
          'Awe',
          'Doma',
          'Karu',
          'Keana',
          'Keffi',
          'Kokona',
          'Lafia',
          'Nasarawa',
          'Nasarawa-Eggon',
          'Obi',
          'Toto',
          'Wamba'
        ),
        'NI' => array(
          'Agaie',
          'Agwara',
          'Bida',
          'Borgu',
          'Bosso',
          'Chanchaga',
          'Edati',
          'Gbako',
          'Gurara',
          'Katcha',
          'Kontagora',
          'Lapai',
          'Lavun',
          'Magama',
          'Mariga',
          'Mashegu',
          'Mokwa',
          'Muya',
          'Pailoro',
          'Rafi',
          'Rijau',
          'Shiroro',
          'Suleja',
          'Tafa',
          'Wushishi'
        ),
        'OG'  => array(
          'Abeokuta North',
          'Abeokuta South',
          'Ado-Odo/Ota',
          'Egbado North',
          'Egbado South',
          'Ewekoro',
          'Ifo',
          'Ijebu East',
          'Ijebu North',
          'Ijebu North East',
          'Ijebu Ode',
          'Ikenne',
          'Imeko-Afon',
          'Ipokia',
          'Obafemi-Owode',
          'Ogun Waterside',
          'Odeda',
          'Odogbolu',
          'Remo North',
          'Shagamu'
        ),
        'ON' => array(
          'Akoko North East',
          'Akoko North West',
          'Akoko South Akure East',
          'Akoko South West',
          'Akure North',
          'Akure South',
          'Ese-Odo',
          'Idanre',
          'Ifedore',
          'Ilaje',
          'Ile-Oluji',
          'Okeigbo',
          'Irele',
          'Odigbo',
          'Okitipupa',
          'Ondo East',
          'Ondo West',
          'Ose',
          'Owo'
        ),
        'OS' => array(
          'Aiyedade',
          'Aiyedire',
          'Atakumosa East',
          'Atakumosa West',
          'Boluwaduro',
          'Boripe',
          'Ede North',
          'Ede South',
          'Egbedore',
          'Ejigbo',
          'Ife Central',
          'Ife East',
          'Ife North',
          'Ife South',
          'Ifedayo',
          'Ifelodun',
          'Ila',
          'Ilesha East',
          'Ilesha West',
          'Irepodun',
          'Irewole',
          'Isokan',
          'Iwo',
          'Obokun',
          'Odo-Otin',
          'Ola-Oluwa',
          'Olorunda',
          'Oriade',
          'Orolu',
          'Osogbo'
        ),
        'OY' => array(
          'Afijio',
          'Akinyele',
          'Atiba',
          'Atigbo',
          'Egbeda',
          'Ibadan Central',
          'Ibadan North',
          'Ibadan North West',
          'Ibadan South East',
          'Ibadan South West',
          'Ibarapa Central',
          'Ibarapa East',
          'Ibarapa North',
          'Ido',
          'Irepo',
          'Iseyin',
          'Itesiwaju',
          'Iwajowa',
          'Kajola',
          'Lagelu Ogbomosho North',
          'Ogbmosho South',
          'Ogo Oluwa',
          'Olorunsogo',
          'Oluyole',
          'Ona-Ara',
          'Orelope',
          'Ori Ire',
          'Oyo East',
          'Oyo West',
          'Saki East',
          'Saki West',
          'Surulere-oyo'
        ),
        'PL' => array(
          'Barikin Ladi',
          'Bassa',
          'Bokkos',
          'Jos East',
          'Jos North',
          'Jos South',
          'Kanam',
          'Kanke',
          'Langtang North',
          'Langtang South',
          'Mangu',
          'Mikang',
          'Pankshin',
          'Qua\'an Pan',
          'Riyom',
          'Shendam',
          'Wase'
        ),
        'RI' => array(
          'Abua/Odual',
          'Ahoada East',
          'Ahoada West',
          'Akuku Toru',
          'Andoni',
          'Asari-Toru',
          'Bonny',
          'Degema',
          'Emohua',
          'Eleme',
          'Etche',
          'Gokana',
          'Ikwerre',
          'Khana',
          'Obia/Akpor',
          'Ogba/Egbema/Ndoni',
          'Ogu/Bolo',
          'Okrika',
          'Omumma',
          'Opobo/Nkoro',
          'Oyigbo',
          'Port-Harcourt',
          'Tai'
        ),
        'SO' => array(
          'Binji',
          'Bodinga',
          'Dange-shnsi',
          'Gada',
          'Goronyo',
          'Gudu',
          'Gawabawa',
          'Illela',
          'Isa',
          'Kware',
          'kebbe',
          'Rabah',
          'Sabon birni',
          'Shagari',
          'Silame',
          'Sokoto North',
          'Sokoto South',
          'Tambuwal',
          'Tqngaza',
          'Tureta',
          'Wamako',
          'Wurno',
          'Yabo'
        ),
        'TA' => array(
          'Ardo-kola',
          'Bali',
          'Donga',
          'Gashaka',
          'Cassol',
          'Ibi',
          'Jalingo',
          'Karin-Lamido',
          'Kurmi',
          'Lau',
          'Sardauna',
          'Takum',
          'Ussa',
          'Wukari',
          'Yorro',
          'Zing'
        ),
        'YO' => array(
          'Bade',
          'Bursari',
          'Damaturu',
          'Fika',
          'Fune',
          'Geidam',
          'Gujba',
          'Gulani',
          'Jakusko',
          'Karasuwa',
          'Karawa',
          'Machina',
          'Nangere',
          'Nguru Potiskum',
          'Tarmua',
          'Yunusari',
          'Yusufari'
        ),
        'ZA' => array(
          'Anka',
          'Bakura',
          'Birnin Magaji',
          'Bukkuyum',
          'Bungudu',
          'Gummi',
          'Gusau',
          'Kaura',
          'Namoda',
          'Maradun',
          'Maru',
          'Shinkafi',
          'Talata Mafara',
          'Tsafe',
          'Zurmi'
        ),
        'FC' => array(
          'Gwagwalada',
          'Kuje',
          'Abaji',
          'Abuja Municipal',
          'Bwari',
          'Kwali'
        )
    );
    return $cities;
}